In [1]:
import torch

In [2]:
import torchvision

In [5]:
#this is 1-d tensor
a=torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [6]:
#this is 2-d tensor
b=torch.tensor([ [1,2,3],[2,3,1],[0,1,10],[2,3,10] ])
print(b)

tensor([[ 1,  2,  3],
        [ 2,  3,  1],
        [ 0,  1, 10],
        [ 2,  3, 10]])


In [7]:
#size of a tensor
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())


torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [8]:
# getting the no of rows
print(b.shape[0])

4


In [9]:
# making a DoubleTensor
c=torch.DoubleTensor([[1.1,2.2,3.2],[2,4,4]])
print(c)


tensor([[1.1000, 2.2000, 3.2000],
        [2.0000, 4.0000, 4.0000]], dtype=torch.float64)


In [11]:
#getting datatype of tensor
print(c.dtype)

torch.float64


In [12]:
#getting mean and standard deviation for tensor
print(c.mean())
print(c.std())

tensor(2.7500, dtype=torch.float64)
tensor(1.1760, dtype=torch.float64)


In [13]:
# resize tensor
# if one of the dimension is -1 then other can be inferred

print(b.view(-1,1))
print(b.view(12))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 2],
        [ 3],
        [ 1],
        [ 0],
        [ 1],
        [10],
        [ 2],
        [ 3],
        [10]])
tensor([ 1,  2,  3,  2,  3,  1,  0,  1, 10,  2,  3, 10])


In [ ]:
#for changing it permanently we have to assign also , b=b.view(12,1)

In [15]:
# now create a 3D tensor with 2 channels,3 rows and 4 columns
three_dim=torch.randn(2,3,4)
print(three_dim)

tensor([[[ 0.1303,  0.2460, -0.6496,  1.4130],
         [-1.1850,  0.2391, -0.1815,  0.4960],
         [-0.0804,  1.6873,  0.8309,  1.3578]],

        [[ 0.1365,  0.6257,  0.8353,  0.2533],
         [ 0.1528,  1.0380,  1.3261, -0.8019],
         [ 1.2898, -0.1633, -0.3569, -0.2346]]])


In [17]:
print(three_dim.view(2,12))

tensor([[ 0.1303,  0.2460, -0.6496,  1.4130, -1.1850,  0.2391, -0.1815,  0.4960,
         -0.0804,  1.6873,  0.8309,  1.3578],
        [ 0.1365,  0.6257,  0.8353,  0.2533,  0.1528,  1.0380,  1.3261, -0.8019,
          1.2898, -0.1633, -0.3569, -0.2346]])


In [18]:
# random values b/w 0 and 1 
r=torch.rand(4,4)
print(r)

tensor([[0.4213, 0.1603, 0.4661, 0.6870],
        [0.6705, 0.0708, 0.3876, 0.3845],
        [0.7308, 0.2516, 0.3530, 0.5020],
        [0.3116, 0.4062, 0.2945, 0.2167]])


In [19]:
# random values but having mean = 0 and var = 1
r2=torch.randn(4,4)
print(r2)

tensor([[ 1.5078,  0.4963,  0.8182,  1.4166],
        [-0.6677,  1.0040, -0.9602,  1.0656],
        [ 1.5759, -1.3617, -1.1755,  0.0451],
        [ 0.0157,  0.1271, -0.0364, -0.3154]])


In [21]:
# create array of 5 random integers having values b/w 6 to 9 (both inclusive)
in_array=torch.randint(6,10,(5,))
print(in_array)


tensor([8, 7, 8, 8, 6])


In [22]:
# create 2-d array of 3*3 random integers having values b/w 6 to 9 (both inclusive)
in_array2=torch.randint(6,10,(3,3))
print(in_array2)

tensor([[6, 8, 7],
        [6, 8, 6],
        [6, 6, 7]])


In [23]:
#getting number of elements 
print(torch.numel(in_array))

5


In [33]:
# creating matix of zeros and ones
zero_arr=torch.zeros(3,3)
print(zero_arr)
one_arr=torch.ones(3,3)
print(one_arr)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [36]:
res=torch.add(zero_arr,one_arr)
print(res)
res2=torch.add(one_arr,torch.FloatTensor([[1,2,3],[1,2,3],[1,2,3]]))
print(res2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])


In [42]:
print(res2[:,:])
print(res2[:,:2])
hiten=res2[1,2]
print(hiten)

tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])
tensor([[2., 3.],
        [2., 3.],
        [2., 3.]])
tensor(4.)
